modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://mrcrayfish.com/api/mod_update/neoforge/${mod_id}"
displayURL = "${mod_homepage}"
logoFile = "assets/${mod_id}/banner.png"
authors = "${mod_author}"
description = '''${mod_desc}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "framework"
type = "optional"
versionRange = "[${framework_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "NONE"
side = "BOTH"

[modproperties.${mod_id}]
catalogueImageIcon = "assets/${mod_id}/icon.png"
catalogueBackground = "assets/${mod_id}/background.png"
configuredProviders = [
    "com.mrcrayfish.configured.impl.neoforge.NeoForgeConfigProvider",
    "com.mrcrayfish.configured.impl.framework.FrameworkConfigProvider",
    "com.mrcrayfish.configured.impl.jei.JeiConfigProvider"
]